/*
 * io_config_ext.h
 *
 * Description: Header file declaring the compiler extensions for eia components
 *  Created on: 2018¦~10¤ë26¤é
 *      Author: 902452
 */

#ifndef SOCKET_CONFIGS_24_IO_CONFIG_EXT_H_
#define SOCKET_CONFIGS_24_IO_CONFIG_EXT_H_


typedef enum WEI_IRQ_ID_S{
	WEI_IRQ_ID_PGPIO00 = 78,
	WEI_IRQ_ID_PGPIO01,
	WEI_IRQ_ID_PGPIO02,
	WEI_IRQ_ID_PGPIO03,
	WEI_IRQ_ID_PGPIO04,
	WEI_IRQ_ID_RC36_CAL_FINISH,
	WEI_IRQ_ID_RC36_CAL_OVF,
	WEI_IRQ_ID_PLL_LOCK,
	WEI_IRQ_ID_CPU_REGBK,
	WEI_IRQ_ID_RC36_CAL_DONE,
	WEI_IRQ_ID_APB_UART0_TX,
	WEI_IRQ_ID_APB_UART0_RX,
	WEI_IRQ_ID_APB_UART1_TX = 90,	//90
	WEI_IRQ_ID_APB_UART1_RX,
	WEI_IRQ_ID_PWM0,
	WEI_IRQ_ID_PWM1,
	WEI_IRQ_ID_PWM2,
	WEI_IRQ_ID_ADCC,
	WEI_IRQ_ID_EDM,
	WEI_IRQ_ID_I2S_TX_OR,
	WEI_IRQ_ID_I2S_TX_EMP,
	WEI_IRQ_ID_RTC,
	WEI_IRQ_ID_SSI0	= 100,			//100
	WEI_IRQ_ID_SSI1,
	WEI_IRQ_ID_DMAC,
	WEI_IRQ_ID_CDM_MOTION,
	WEI_IRQ_ID_CDM_ABNORMAL,
	WEI_IRQ_ID_HOG_DMA,
	WEI_IRQ_ID_RS_DMA,
	WEI_IRQ_ID_INP_PARSER_ERR,//WEI_IRQ_ID_SC_NFRAME_END,
	WEI_IRQ_ID_SC_TIMEOUT,
	WEI_IRQ_ID_WDMA1,
	WEI_IRQ_ID_WDMA1_ABNORMAL = 110,	//110
	WEI_IRQ_ID_WDMA2,
	WEI_IRQ_ID_WDMA2_ABNORMAL,
	WEI_IRQ_ID_WDMA3,
	WEI_IRQ_ID_WDMA3_ABNORMAL,
	WEI_IRQ_ID_RDMA,
	WEI_IRQ_ID_RDMA_ABNORMAL,
	WEI_IRQ_ID_SEN_INT,
	WEI_IRQ_ID_INP_VSIN,
	WEI_IRQ_ID_INP_HSIN,
	WEI_IRQ_ID_INP_VSOUT = 120,		//120
	WEI_IRQ_ID_INP_HSOUT,
	WEI_IRQ_ID_WDMA1_VS,
	WEI_IRQ_ID_WDMA1_HS,
	WEI_IRQ_ID_WDMA2_VS,
	WEI_IRQ_ID_WDMA2_HS,
	WEI_IRQ_ID_WDMA3_VS,
	WEI_IRQ_ID_WDMA3_HS,
	WEI_IRQ_ID_PMU_ADC_TIMEOUT,
	WEI_IRQ_ID_I2S_RX_OR,
	WEI_IRQ_ID_I2S_RX_DA = 130,		//130
	WEI_IRQ_ID_INP_S2P_ERR,
	WEI_IRQ_ID_SC_NFRAME_END,//WEI_IRQ_ID_INP_PARSER_ERR,
	WEI_IRQ_ID_RTC_ADC,
	WEI_IRQ_ID_PMU_TIMEOUT,
	WEI_IRQ_ID_RESERVED4,
	WEI_IRQ_ID_PGPIO05,
	WEI_IRQ_ID_PGPIO06,
	WEI_IRQ_ID_PGPIO07,
	WEI_IRQ_ID_PGPIO08,
	WEI_IRQ_ID_PGPIO09 = 140,			//140
	WEI_IRQ_ID_PGPIO10,
	WEI_IRQ_ID_PGPIO11,
	WEI_IRQ_ID_PGPIO12,
	WEI_IRQ_ID_PGPIO13,
	WEI_IRQ_ID_PGPIO14,
	WEI_IRQ_ID_SGPIO00,
	WEI_IRQ_ID_SGPIO01,
	WEI_IRQ_ID_SEC_EPI130,
	WEI_IRQ_ID_SEC_HOST0,
	WEI_IRQ_ID_SEC_HOST1 = 150,		//150
	WEI_IRQ_ID_SEC_HOST2,
	WEI_IRQ_ID_OTP_READY,
	WEI_IRQ_ID_RC32_CAL_DONE,
	WEI_IRQ_ID_RC32_CAL_FINISH,
	WEI_IRQ_ID_RC32_CAL_OVF,
	WEI_IRQ_ID_INP_RX_DE_HCNT_ERROR_INT,
	WEI_IRQ_ID_INP_RX2OUT_DE_HCNT_ERROR_INT
}WEI_IRQ_ID_E;

// Interrupt connection for peripheral <without DFSS>
#define IO_PWM_PRESENT
#define INTNO_PWM0						(WEI_IRQ_ID_PWM0)
#define INTNO_PWM1						(WEI_IRQ_ID_PWM1)
#define INTNO_PWM2						(WEI_IRQ_ID_PWM2)

#define IO_SPI_MST0_DW_PRESENT
#define INTNO_SPI_DW_MST0		    	(WEI_IRQ_ID_SSI0)

#define IO_SPI_MST1_DW_PRESENT
#define INTNO_SPI_DW_MST1		    	(WEI_IRQ_ID_SSI1)

#define IO_RTC_HMX_PRESENT
#define IO_RTC_SEN_HMX_INTR             (WEI_IRQ_ID_RTC)
#define IO_RTC_ADC_HMX_INTR             (WEI_IRQ_ID_RTC_ADC)


#define IO_GPIO_HMX_PRESENT
#define IO_GPIO_HMX_PGPIO00            	(WEI_IRQ_ID_PGPIO00)
#define IO_GPIO_HMX_PGPIO01            	(WEI_IRQ_ID_PGPIO01)
#define IO_GPIO_HMX_PGPIO02            	(WEI_IRQ_ID_PGPIO02)
#define IO_GPIO_HMX_PGPIO03            	(WEI_IRQ_ID_PGPIO03)
#define IO_GPIO_HMX_PGPIO04           	(WEI_IRQ_ID_PGPIO04)
#define IO_GPIO_HMX_PGPIO05            	(WEI_IRQ_ID_PGPIO05)
#define IO_GPIO_HMX_PGPIO06            	(WEI_IRQ_ID_PGPIO06)
#define IO_GPIO_HMX_PGPIO07            	(WEI_IRQ_ID_PGPIO07)
#define IO_GPIO_HMX_PGPIO08            	(WEI_IRQ_ID_PGPIO08)
#define IO_GPIO_HMX_PGPIO09           	(WEI_IRQ_ID_PGPIO09)
#define IO_GPIO_HMX_PGPIO10            	(WEI_IRQ_ID_PGPIO10)
#define IO_GPIO_HMX_PGPIO11           	(WEI_IRQ_ID_PGPIO11)
#define IO_GPIO_HMX_PGPIO12           	(WEI_IRQ_ID_PGPIO12)
#define IO_GPIO_HMX_PGPIO13            	(WEI_IRQ_ID_PGPIO13)
#define IO_GPIO_HMX_PGPIO14           	(WEI_IRQ_ID_PGPIO14)
#define IO_GPIO_HMX_SGPIO00            	(WEI_IRQ_ID_SGPIO00)
#define IO_GPIO_HMX_SGPIO01            	(WEI_IRQ_ID_SGPIO01)

//PMU
#define IO_PMU_INT_PRESENT
#define IO_PMU_RC36_CAL_FINISH_INT		(WEI_IRQ_ID_RC36_CAL_FINISH)
#define IO_PMU_RC36_CAL_OVF_INT			(WEI_IRQ_ID_RC36_CAL_OVF)
#define IO_PMU_RC36_CAL_DONE_INT		(WEI_IRQ_ID_RC36_CAL_DONE)

#define IO_PMU_RC32_CAL_FINISH_INT		(WEI_IRQ_ID_RC32_CAL_FINISH)
#define IO_PMU_RC32_CAL_OVF_INT			(WEI_IRQ_ID_RC32_CAL_OVF)
#define IO_PMU_RC32_CAL_DONE_INT		(WEI_IRQ_ID_RC32_CAL_DONE)


#define IO_PMU_WDT_INT_PRESENT
#define IO_PMU_WDT_TIMEOUT_INT				(WEI_IRQ_ID_PMU_TIMEOUT)
#define IO_PMU_ADC_TIMEOUT_INT				(WEI_IRQ_ID_PMU_ADC_TIMEOUT) // TODO: wait RD to update ADC TIMEOUT INT NO

//xDMA
#define IO_XDMA_WDMA1_NORMAL_INT   		 (WEI_IRQ_ID_WDMA1)
#define IO_XDMA_WDMA2_NORMAL_INT   		 (WEI_IRQ_ID_WDMA2)
#define IO_XDMA_WDMA3_NORMAL_INT   		 (WEI_IRQ_ID_WDMA3)
#define IO_XDMA_RDMA_NORMAL_INT   		 (WEI_IRQ_ID_RDMA)
#define IO_XDMA_WDMA1_ABNORMAL_INT   	 (WEI_IRQ_ID_WDMA1_ABNORMAL)
#define IO_XDMA_WDMA2_ABNORMAL_INT   	 (WEI_IRQ_ID_WDMA2_ABNORMAL)
#define IO_XDMA_WDMA3_ABNORMAL_INT   	 (WEI_IRQ_ID_WDMA3_ABNORMAL)
#define IO_XDMA_RDMA_ABNORMAL_INT   	 (WEI_IRQ_ID_RDMA_ABNORMAL)

#define IO_XDMA_WDMA1_VS_OUT_INT         (WEI_IRQ_ID_WDMA1_VS)
#define IO_XDMA_WDMA1_HS_OUT_INT         (WEI_IRQ_ID_WDMA1_HS)
#define IO_XDMA_WDMA2_VS_OUT_INT         (WEI_IRQ_ID_WDMA2_VS)
#define IO_XDMA_WDMA2_HS_OUT_INT         (WEI_IRQ_ID_WDMA2_HS)
#define IO_XDMA_WDMA3_VS_OUT_INT         (WEI_IRQ_ID_WDMA3_VS)
#define IO_XDMA_WDMA3_HS_OUT_INT         (WEI_IRQ_ID_WDMA3_HS)

//DataPath
#define IO_DP_CDM_MOTION_INT   		 	 (WEI_IRQ_ID_CDM_MOTION)
#define IO_DP_ABNORMAL_INT           	 (WEI_IRQ_ID_CDM_ABNORMAL)

//HOGDMA
#define IO_HOGDMA_INT   		     	 (WEI_IRQ_ID_HOG_DMA)

//INP
#define IO_INP_VS_IN_INT	   		     (WEI_IRQ_ID_INP_VSIN)
#define IO_INP_VS_OUT_INT	   		     (WEI_IRQ_ID_INP_VSOUT)
#define IO_INP_HS_IN_INT	   		     (WEI_IRQ_ID_INP_HSIN)
#define IO_INP_HS_OUT_INT	   		     (WEI_IRQ_ID_INP_HSOUT)
#define IO_INP_S2P_ERR_INT	   		     (WEI_IRQ_ID_INP_S2P_ERR)

//INP 1BIT PARSER
#define IO_INP1BITPARSER_ERR	   		(WEI_IRQ_ID_INP_PARSER_ERR)

//RSDMA
#define IO_RSDMA_INT	   		     	(WEI_IRQ_ID_RS_DMA)

//SENSOR CONTROL
#define IO_SC_NFRAME_END_INT  	     	(WEI_IRQ_ID_SC_NFRAME_END)
#define IO_SC_TRIGGER_TIMEOUT        	(WEI_IRQ_ID_SC_TIMEOUT)

//SENSOR INT
#define IO_SENSOR_INT  	     			(WEI_IRQ_ID_SEN_INT)

//ADCC
#define IO_ADCC_INT					 	(WEI_IRQ_ID_ADCC)

#define IO_EDM_INT   		     		(WEI_IRQ_ID_EDM)

/* I2S */
#define INTNO_I2S_TX_EMP_0_INTR			(WEI_IRQ_ID_I2S_TX_EMP)
#define INTNO_I2S_TX_OR_0_INTR 			(WEI_IRQ_ID_I2S_TX_OR)
#define INTNO_I2S_RX_DA_0_INTR			(WEI_IRQ_ID_I2S_RX_DA)
#define INTNO_I2S_RX_OR_0_INTR			(WEI_IRQ_ID_I2S_RX_OR)

#endif /* SOCKET_CONFIGS_24_IO_CONFIG_EXT_H_ */
