##
# \brief	definitions for source codes directories
##

## Device HAL Related ##
DEVHAL_ASMSRCDIR	=
DEVHAL_CSRCDIR		=
DEVHAL_CXXSRCDIR	=
DEVHAL_INCDIR		=

## Extra Related ##
### These source code will not be compiled and linked as library
EXTRA_ASMSRCDIR		+=
EXTRA_CSRCDIR		+=
EXTRA_CXXSRCDIR		+=
EXTRA_INCDIR		+= $(EMBARC_ROOT)/inc $(EMBARC_ROOT)/inc/arc $(EMBARC_GENERATED_DIR) $(EMBARC_ROOT)/library/common $(EMBARC_ROOT)/external/cis/hm_common

###############################################################################
## ALL ##
CSRCS_DIR		= $(CPU_CSRCDIR) $(OS_CSRCDIR) $(DEVHAL_CSRCDIR) $(BOARD_CSRCDIR) \
				$(MID_CSRCDIR) $(LIB_CSRCDIR) $(EXTRA_CSRCDIR) $(INTEGRATE_CSRCDIR) $(HWACCAUTOTEST_CSRCDIR) $(SCENARIO_APP_CSRCDIR) $(EVENTHANDLER_CSRCDIR) $(APPL_CSRC_DIR) 
CXXSRCS_DIR		= $(CPU_CXXSRCDIR) $(OS_CXXSRCDIR) $(DEVHAL_CXXSRCDIR) $(BOARD_CXXSRCDIR) \
				$(MID_CXXSRCDIR) $(LIB_CXXSRCDIR) $(EXTRA_CXXSRCDIR) $(INTEGRATE_CXXSRCDIR) $(HWACCAUTOTEST_CXXSRCDIR) $(SCENARIO_APP_CXXSRCDIR) $(EVENTHANDLER_CXXSRCDIR) $(APPL_CXXSRC_DIR)
CCSRCS_DIR		= $(CPU_CCSRCDIR) $(OS_CCSRCDIR) $(DEVHAL_CCSRCDIR) $(BOARD_CCSRCDIR) \
				$(MID_CCSRCDIR) $(LIB_CCSRCDIR) $(EXTRA_CCSRCDIR) $(INTEGRATE_CCSRCDIR) $(HWACCAUTOTEST_CCSRCDIR) $(SCENARIO_APP_CCSRCDIR) $(EVENTHANDLER_CCSRCDIR) $(APPL_CCSRC_DIR)				
ASMSRCS_DIR		= $(CPU_ASMSRCDIR) $(OS_ASMSRCDIR) $(DEVHAL_ASMSRCDIR) $(BOARD_ASMSRCDIR) \
				$(MID_ASMSRCDIR) $(LIB_ASMSRCDIR) $(EXTRA_ASMSRCDIR) $(INTEGRATE_ASMSRCDIR) $(HWACCAUTOTEST_ASMSRCDIR) $(SCENARIO_APP_ASMSRCDIR) $(EVENTHANDLER_ASMSRCDIR) $(APPL_ASMSRC_DIR)
INCS_DIR		= $(CPU_INCDIR) $(OS_INCDIR) $(DEVHAL_INCDIR) $(BOARD_INCDIR) \
				$(MID_INCDIR) $(LIB_INCDIR) $(EXTRA_INCDIR) $(INTEGRATE_INCDIR) $(HWACCAUTOTEST_INCDIR) $(SCENARIO_APP_INCDIR) $(EVENTHANDLER_INCDIR) $(APPL_INC_DIR)
###############################################################################

##
# Collect Application Source Files
##
APPL_CSRCS += $(call get_csrcs, $(APPL_CSRC_DIR))
APPL_ASMSRCS += $(call get_asmsrcs, $(APPL_ASMSRC_DIR))
APPL_CXXSRCS += $(call get_cxxsrcs, $(APPL_CXXSRC_DIR))

##
# Collect Extra Source Files
##
EXTRA_CSRCS += $(call get_csrcs, $(EXTRA_CSRCDIR))
EXTRA_ASMSRCS += $(call get_asmsrcs, $(EXTRA_ASMSRCDIR))
EXTRA_CXXSRCS += $(call get_cxxsrcs, $(EXTRA_CXXSRCDIR))

##
# Collect Application Object Files
##
APPL_COBJS = $(call get_appobjs, $(APPL_CSRCS))
APPL_ASMOBJS = $(call get_appobjs, $(APPL_ASMSRCS))
APPL_CXXOBJS = $(call get_appobjs, $(APPL_CXXSRCS))
APPL_CCOBJS = $(call get_appobjs, $(APPL_CCSRCS))
APPL_OBJS = $(APPL_COBJS) $(APPL_ASMOBJS) $(APPL_CXXOBJS) $(APPL_CCOBJS)

##
# Collect Extra Object Files
##
EXTRA_COBJS = $(call get_relobjs, $(EXTRA_CSRCS))
EXTRA_ASMOBJS = $(call get_relobjs, $(EXTRA_ASMSRCS))
EXTRA_CXXOBJS = $(call get_relobjs, $(EXTRA_CXXSRCS))
EXTRA_CCOBJS = $(call get_relobjs, $(EXTRA_CCSRCS))
EXTRA_OBJS = $(EXTRA_COBJS) $(EXTRA_ASMOBJS) $(EXTRA_CXXOBJS) $(EXTRA_CCOBJS)

##
# Collect Integrate CLI Object Files
##
INTEGRATE_COBJS = $(call get_relobjs, $(INTEGRATE_CSRCS))
INTEGRATE_ASMOBJS = $(call get_relobjs, $(INTEGRATE_ASMSRCS))
INTEGRATE_CXXOBJS = $(call get_relobjs, $(INTEGRATE_CXXSRCS))
INTEGRATE_CCOBJS = $(call get_relobjs, $(INTEGRATE_CCSRCS))
INTEGRATE_OBJS = $(INTEGRATE_COBJS) $(INTEGRATE_ASMOBJS) $(INTEGRATE_CXXOBJS) $(INTEGRATE_CCOBJS)

HWACCAUTOTEST_COBJS = $(call get_relobjs, $(HWACCAUTOTEST_CSRCS))
HWACCAUTOTEST_ASMOBJS = $(call get_relobjs, $(HWACCAUTOTEST_ASMSRCS))
HWACCAUTOTEST_CXXOBJS = $(call get_relobjs, $(HWACCAUTOTEST_CXXSRCS))
HWACCAUTOTEST_CCOBJS = $(call get_relobjs, $(HWACCAUTOTEST_CCSRCS))
HWACCAUTOTEST_OBJS = $(HWACCAUTOTEST_COBJS) $(HWACCAUTOTEST_ASMOBJS) $(HWACCAUTOTEST_CXXOBJS) $(HWACCAUTOTEST_CCOBJS)

SCENARIO_APP_COBJS = $(call get_relobjs, $(SCENARIO_APP_CSRCS))
SCENARIO_APP_ASMOBJS = $(call get_relobjs, $(SCENARIO_APP_ASMSRCS))
SCENARIO_APP_CXXOBJS = $(call get_relobjs, $(SCENARIO_APP_CXXSRCS))
SCENARIO_APP_CCOBJS = $(call get_relobjs, $(SCENARIO_APP_CCSRCS))
SCENARIO_APP_OBJS = $(SCENARIO_APP_COBJS) $(SCENARIO_APP_ASMOBJS) $(SCENARIO_APP_CXXOBJS) $(SCENARIO_APP_CCOBJS)

EVENTHANDLER_COBJS = $(call get_relobjs, $(EVENTHANDLER_CSRCS))
EVENTHANDLER_ASMOBJS = $(call get_relobjs, $(EVENTHANDLER_CXXSRCS))
EVENTHANDLER_CXXOBJS = $(call get_relobjs, $(EVENTHANDLER_ASMSRCS))
EVENTHANDLER_CCOBJS = $(call get_relobjs, $(EVENTHANDLER_CCSRCS))
EVENTHANDLER_OBJS = $(EVENTHANDLER_COBJS) $(EVENTHANDLER_ASMOBJS) $(EVENTHANDLER_CXXOBJS) $(EVENTHANDLER_CCOBJS)

#########ALL DIRECTOIRES & SOURCE FILES & OBJECT FILES COLLECTION#############
##
# Collect all include/c/asm/cpp directories
##
ALL_INC_DIRS = $(sort $(INCS_DIR))
ALL_CSRC_DIRS = $(sort $(CSRCS_DIR))
ALL_CCSRC_DIRS = $(sort $(CCSRCS_DIR))
ALL_ASMSRC_DIRS = $(sort $(ASMSRCS_DIR))
ALL_CXXSRC_DIRS = $(sort $(CXXSRCS_DIR))

##
# Collect all sources files
##
ALL_CSRCS = $(sort $(CPU_CSRCS) $(BOARD_CSRCS) $(LIB_CSRCS) $(CV_LIB_CSRCS) $(BSS_LIB_CSRCS) $(MID_CSRCS) $(AZ_SDK_LIB_CSRCS) $(NETXDUO_LIB_CSRCS) $(OS_CSRCS) $(APPL_CSRCS) $(EXTRA_CSRCS) $(INTEGRATE_CSRCS) $(HWACCAUTOTEST_CSRCS) $(SCENARIO_APP_CSRCS) $(EVENTHANDLER_CSRCS))
ALL_ASMSRCS = $(sort $(CPU_ASMSRCS) $(BOARD_ASMSRCS) $(LIB_ASMSRCS) $(CV_LIB_ASMSRCS) $(BSS_LIB_ASMSRCS) $(MID_ASMSRCS) $(AZ_SDK_LIB_ASMSRCS) $(NETXDUO_LIB_ASMSRCS) $(OS_ASMSRCS) $(APPL_ASMSRCS) $(EXTRA_ASMSRCS) $(INTEGRATE_ASMSRCS) $(HWACCAUTOTEST_ASMSRCS) $(SCENARIO_APP_ASMSRCS) $(EVENTHANDLER_ASMSRCS))
ALL_CXXSRCS = $(sort $(CPU_CXXSRCS) $(BOARD_CXXSRCS) $(LIB_CXXSRCS) $(CV_LIB_CXXSRCS) $(BSS_LIB_CXXSRCS) $(MID_CXXSRCS) $(AZ_SDK_LIB_CXXSRCS) $(NETXDUO_LIB_CXXSRCS) $(OS_CXXSRCS) $(APPL_CXXSRCS) $(EXTRA_CXXSRCS) $(INTEGRATE_CXXSRCS) $(HWACCAUTOTEST_CXXSRCS) $(SCENARIO_APP_CXXSRCS) $(EVENTHANDLER_CXXSRCS))
ALL_CCSRCS = $(sort $(CPU_CCSRCS) $(BOARD_CCSRCS) $(LIB_CCSRCS) $(CV_LIB_CCSRCS) $(MID_CCSRCS) $(AZ_SDK_LIB_CCSRCS) $(NETXDUO_LIB_CCSRCS) $(OS_CCSRCS) $(APPL_CCSRCS) $(EXTRA_CCSRCS) $(INTEGRATE_CCSRCS) $(HWACCAUTOTEST_CCSRCS) $(SCENARIO_APP_CCSRCS) $(EVENTHANDLER_CCSRCS))
ALL_ALLSRCS = $(sort $(ALL_CSRCS) $(ALL_ASMSRCS) $(ALL_CXXSRCS) $(ALL_CCSRCS))

##
# Collect all object files
##
ALL_COBJS = $(sort $(CPU_COBJS) $(BOARD_COBJS) $(LIB_COBJS) $(BOARD_SOCKET_OPEN_OBJS) $(CV_LIB_COBJS) $(BSS_LIB_COBJS) $(MID_COBJS) $(OS_COBJS) $(AZ_SDK_LIB_COBJS) $(NETXDUO_LIB_COBJS) $(APPL_COBJS) $(EXTRA_COBJS) $(INTEGRATE_COBJS) $(HWACCAUTOTEST_COBJS) $(SCENARIO_APP_COBJS) $(EVENTHANDLER_COBJS))
ALL_ASMOBJS = $(sort $(CPU_ASMOBJS) $(BOARD_ASMOBJS) $(LIB_ASMOBJS) $(CV_LIB_ASMOBJS) $(BSS_LIB_ASMOBJS) $(MID_ASMOBJS) $(AZ_SDK_LIB_ASMOBJS) $(NETXDUO_LIB_ASMOBJS) $(OS_ASMOBJS) $(APPL_ASMOBJS) $(EXTRA_ASMOBJS) $(INTEGRATE_ASMOBJS) $(HWACCAUTOTEST_ASMOBJS) $(SCENARIO_APP_ASMOBJS) $(EVENTHANDLER_ASMOBJS))
ALL_CXXOBJS = $(sort $(CPU_CXXOBJS) $(BOARD_CXXOBJS) $(LIB_CXXOBJS) $(CV_LIB_CXXOBJS) $(BSS_LIB_CXXOBJS) $(MID_CXXOBJS) $(AZ_SDK_LIB_CXXOBJS) $(NETXDUO_LIB_CXXOBJS) $(OS_CXXOBJS) $(APPL_CXXOBJS) $(EXTRA_CXXOBJS) $(INTEGRATE_CXXOBJS) $(HWACCAUTOTEST_CXXOBJS) $(SCENARIO_APP_CXXOBJS) $(EVENTHANDLER_CXXOBJS))
ALL_CCOBJS = $(sort $(CPU_CCOBJS) $(BOARD_CCOBJS) $(LIB_CCOBJS) $(CV_LIB_CCOBJS) $(MID_CCOBJS) $(AZ_SDK_LIB_CCOBJS) $(NETXDUO_LIB_CCOBJS) $(OS_CCOBJS) $(APPL_CCOBJS) $(EXTRA_CCOBJS) $(INTEGRATE_CCOBJS) $(HWACCAUTOTEST_CCOBJS) $(SCENARIO_APP_CCOBJS) $(EVENTHANDLER_CCOBJS))
ALL_ALLOBJS = $(sort $(ALL_COBJS) $(ALL_ASMOBJS) $(ALL_CXXOBJS) $(ALL_CCOBJS))
##############################################################################