# platform root declaration
SCENARIO_APP_ROOT = $(EMBARC_ROOT)/app/scenario_app

SCENARIO_APP_MKS =
SCENARIO_APP_MKS += $(foreach APP_TYPE_MK, $(APP_TYPE), $(wildcard $(SCENARIO_APP_ROOT)/$(APP_TYPE_MK)/*.mk))
include $(wildcard $(SCENARIO_APP_MKS))
# cli_global_cmd
SCENARIO_APP_REQUIRED = 

SCENARIO_APP_INCDIR = $(SCENARIO_APP_ROOT)

SCENARIO_APP_CSRCDIR = 
SCENARIO_APP_CXXSRCDIR = 
SCENARIO_APP_CCSRCDIR = 
SCENARIO_APP_ASMSRCDIR = 

SCENARIO_APP_CSRCS =  
SCENARIO_APP_CXXSRCS =
SCENARIO_APP_CCSRCS =
SCENARIO_APP_ASMSRCS =
SCENARIO_APP_ALLSRCS = 

SCENARIO_APP_COBJS = 
SCENARIO_APP_CXXOBJS =
SCENARIO_APP_CCOBJS =  
SCENARIO_APP_ASMOBJS = 
SCENARIO_APP_ALLOBJS =

SCENARIO_APP_DEFINES =
SCENARIO_APP_DEPS =
SCENARIO_APP_LIBS =

# extra macros to be defined
LIB_SCENARIO_APP_DEFINES = 

# genearte library
LIB_SCENARIO_APP= $(OUT_DIR)/libscenario_app.a


ifdef SCENARIO_APP_SUPPORT_LIST
	override SCENARIO_APP_SUPPORT_LIST  := $(sort $(strip $(SCENARIO_APP_REQUIRED) $(SCENARIO_APP_SUPPORT_LIST)))
	SCENARIO_APP_SUPPORT_SORTED = $(sort $(SCENARIO_APP_SUPPORT_LIST))		
	SCENARIO_APP_CSRCDIR += $(foreach SCENARIO_APP_CLI, $(SCENARIO_APP_SUPPORT_SORTED), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_CCSRCDIR += $(foreach SCENARIO_APP_CLI, $(SCENARIO_APP_SUPPORT_SORTED), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_CXXSRCDIR += $(foreach SCENARIO_APP_CLI, $(SCENARIO_APP_SUPPORT_SORTED), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_INCDIR += $(foreach SCENARIO_APP_CLI, $(SCENARIO_APP_SUPPORT_SORTED), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))

ifneq ($(EVENTHANDLER_SUPPORT), "")		
	SCENARIO_APP_CSRCDIR += $(foreach SCENARIO_APP_CLI, $(EVENTHANDLER_SUPPORT), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_CXXSRCDIR += $(foreach SCENARIO_APP_CLI, $(EVENTHANDLER_SUPPORT), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_CCSRCDIR += $(foreach SCENARIO_APP_CLI, $(EVENTHANDLER_SUPPORT), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_INCDIR += $(foreach SCENARIO_APP_CLI, $(EVENTHANDLER_SUPPORT), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))

	override EVENTHANDLER_SUPPORT_LIST  := $(sort $(strip $(SCENARIO_APP_REQUIRED) $(EVENTHANDLER_SUPPORT_LIST)))
	EVENTHANDLER_SUPPORT_SORTED = $(sort $(EVENTHANDLER_SUPPORT_LIST))		
	SCENARIO_APP_CSRCDIR += $(foreach SCENARIO_APP_CLI, $(EVENTHANDLER_SUPPORT_SORTED), $(addprefix $(SCENARIO_APP_ROOT)/$(EVENTHANDLER_SUPPORT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_CXXSRCDIR += $(foreach SCENARIO_APP_CLI, $(EVENTHANDLER_SUPPORT_SORTED), $(addprefix $(SCENARIO_APP_ROOT)/$(EVENTHANDLER_SUPPORT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_CCSRCDIR += $(foreach SCENARIO_APP_CLI, $(EVENTHANDLER_SUPPORT_SORTED), $(addprefix $(SCENARIO_APP_ROOT)/$(EVENTHANDLER_SUPPORT)/, $(SCENARIO_APP_CLI)))	
	SCENARIO_APP_INCDIR += $(foreach SCENARIO_APP_CLI, $(EVENTHANDLER_SUPPORT_SORTED), $(addprefix $(SCENARIO_APP_ROOT)/$(EVENTHANDLER_SUPPORT)/, $(SCENARIO_APP_CLI)))
endif

ifneq ($(SUPPORT_STANDALONE), "")		
	SCENARIO_APP_CSRCDIR += $(foreach SCENARIO_APP_CLI, $(SUPPORT_STANDALONE), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_CXXSRCDIR += $(foreach SCENARIO_APP_CLI, $(SUPPORT_STANDALONE), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_CCSRCDIR += $(foreach SCENARIO_APP_CLI, $(SUPPORT_STANDALONE), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
	SCENARIO_APP_INCDIR += $(foreach SCENARIO_APP_CLI, $(SUPPORT_STANDALONE), $(addprefix $(SCENARIO_APP_ROOT)/, $(SCENARIO_APP_CLI)))
endif

ifeq ($(USE_APP_API), y)
	SCENARIO_APP_CSRCS = $(APPL_APP_CSRCS)
	SCENARIO_APP_CCSRCS = $(APPL_APP_CCSRCS)
	SCENARIO_APP_INCDIR += $(APPL_APP_INCDIRS)
	SCENARIO_APP_CSRCS += $(APPL_API_SRCS)
	SCENARIO_APP_INCDIR += $(APPL_API_INCDIRS)
else
	SCENARIO_APP_CSRCS = $(call get_csrcs, $(SCENARIO_APP_CSRCDIR))
	SCENARIO_APP_CXXSRCS = $(call get_cxxsrcs, $(SCENARIO_APP_CXXSRCDIR))
	SCENARIO_APP_CCSRCS = $(call get_ccsrcs, $(SCENARIO_APP_CCSRCDIR))
	SCENARIO_APP_ASMSRCS = $(call get_asmsrcs, $(SCENARIO_APP_ASMSRCDIR))
endif

endif


